### ISSUE TITLE
Support JSON serialisation of lists and maps

### ISSUE THREAD

**Issue by pstutz** [opencypher/cypher-for-apache-spark#180]
https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/test/scala/org/opencypher/caps/web/CAPSJsonSerialiserTest.scala#L28

**Comment by DarthMax** [comment]
I just realized, that we serialize all CypherValues to Strings, although JSON supports an equivalent data type: eg a CTBoolean(false) becomes `"false"` instead of `false` and a CTInteger(42) becomes `"42"` instead of `42`. Is that the intended behavior and if so, would a CTList(1,2,3) also become `"[1, 2, 3]"` or even `"['1','2','3']'` instead of simply `[1,2,3]`?

**Comment by Mats-SX** [comment]
It is intended, yes, for consistency and simplicity reasons. I don't have any strong arguments against changing it for the types that are directly supported.

**Comment by Mats-SX** [comment]
Actually, there are exceptions: the ids of entities are serialised to JSON integers.

This comment details the format: https://github.com/opencypher/cypher-for-apache-spark/blob/3afbaabb55d6ec808e7b181f80911e332fef8aa1/src/main/scala/org/opencypher/caps/web/CAPSJsonSerialiser.scala#L117-L173
