### ISSUE TITLE
Support neo4j-apoc-procedures

### ISSUE THREAD

**Issue by zhiboz** [opencypher/cypher-for-apache-spark#230]
Any plan to support [apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures) and other procedures in [graph-algo](https://neo4j-contrib.github.io/neo4j-graph-algorithms/)?

**Comment by Mats-SX** [comment]
Hello @zhiboz and apologies for the very late reply.

There isn't any easy way of directly porting either apoc or graph-algos built for Neo4j to CAPS. In order to do so we would need to implement the API towards which these are built, and that API is designed for a native graph database and not a distributed SQL processing platform -- a difficult task.

We do intend to open the door for user-defined functions and procedures however. Whether we can find a migration route for already-existing procedures and functions (such as those in apoc) is hard to say at this point.
