### ISSUE TITLE
Test CsvGraphSources configured with an empty directory

### ISSUE THREAD

**Issue by Mats-SX** [opencypher/cypher-for-apache-spark#366]
During the training somebody reported that pointing the csv-based PGDSs to an empty directory produced an error due to some missing directory. These should (attempt to) create any missing expected directories.

**Comment by s1ck** [comment]
I tried to verify that behavior. When writing the graph into an empty folder, the `nodes` and `relationships` folders are generated by the specific `CSVFileHandler` implementation. An exception is raised when one tries to read a graph from an empty folder. However, since the data source expects at least one node file + schema, we would need to change that code in order to create an empty node scan if no data is present. I wonder if this is a common use case to support, i.e. reading an empty graph via a data source.

**Comment by Mats-SX** [comment]
I didn't mean we should support reading an empty graph if the directory is missing. I mean we should just not crash, but just state that there are no graphs in there yet.
