### ISSUE TITLE
Entity variables in planners have the wrong CypherType

### ISSUE THREAD

**Issue by DarthMax** [opencypher/cypher-for-apache-spark#513]
The AST removes the labels from the pattern and moves them into to `WHERE` clauses. They are later added back in the logical optimizer step. However, typing of the pattern and thus typing of the entity variables already happens at IR planning time. The variables and their CypherTypes are then used as input for subsequent planning phases. This leads to a mismatch of the variables stored in the RecordHeader and the variables references in the operators

**Comment by Mats-SX** [comment]
Where does the "other" variables come from, if they are not the variables produced during IR construction? Do we construct additional variables without label type information during flat planning that end up in the `RecordHeader`?

Do you think we should fix this here or add to the frontend the possibility to normalise these predicates into the pattern instead of the other direction?

**Comment by Mats-SX** [comment]
@DarthMax Do you think this is still an issue? Do you know how to reproduce it?
