### ISSUE TITLE
Does CAPS support streaming dataframes?

### ISSUE THREAD

**Issue by kant111** [opencypher/cypher-for-apache-spark#715]
Does CAPS support streaming dataframes? other words can I issue a cypher query that can construct a graph on streaming data?

**Comment by Mats-SX** [comment]
Hello @kant111 

We haven't been looking at streaming DataFrames specifically, but we do consider them an interesting topic. In theory, it should all work, because we only make use of the Spark SQL API (ie, `DataFrame`), but we haven't done any extensive testing of it to make sure.

Once we get to investigating this we'll make sure to report back. If you want to test it, any experience you could share with us would be greatly appreciated.
