### ISSUE TITLE
Support for UUID as ids

### ISSUE THREAD

**Issue by ram-senth** [opencypher/cypher-for-apache-spark#729]
We at Uber are evaluating adoption of the CAPS library but need support for UUID as ids. I see that the library is limited to Long ids. Is there any gotchas that I should be aware before I attempt changing the library to use UUID? Also is there any design documentation that can help me ramp-up on the library?

**Comment by s1ck** [comment]
Hey. Thanks for your interest in CAPS and sorry for the late reply. 

You are right, we currently enforce the id datatype to Long. However, it is possible to change this to any data type supported by Spark. Unfortunately, Spark has no native support for Java UUIDs. We actually did an experiment using `StringType` and it did not require a lot of changes in the code base.

Before doing this, I was wondering if your use-case involves a static data set. In that case, one could transform / generate identifiers in an independent job, persist the graph and use it for querying. We have tooling for id-generation as part of the [SQL PGDS](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher/src/main/scala/org/opencypher/spark/api/io/sql/SqlPropertyGraphDataSource.scala).

If you wanna adapt the library to handle String ids instead of Long ids, one of the biggest "gotchas" is how we avoid collisions when computing a union over multiple graphs. This is needed during `CONSTRUCT ON` clauses. We currently store a graph identifier (a graph tag) in the upper bits on an identifier. Those tags would need to be encoded into the String-ID, too.

In both cases = generating long ids or changing the id type - we could have a call and discuss the options. Let me know what you think.

I will prepare an up-to-date architecture overview of Okapi/CAPS in the next days and share it in the repo.

**Comment by s1ck** [comment]
Please have a look at these [Google slides](https://docs.google.com/presentation/d/1nuMEbdn-mJCvSsQZLgycLqyC-BsDQd93ZlwPHCbIlTw/edit?usp=sharing) for an overview of the project and its modules. It is probably not as detailed as you'd like. Let me know if you have additional questions.

**Comment by ram-senth** [comment]
Hi Martin, thanks a lot for your time and feedback. The google slides get us started down the path of understanding CAPS library better. Looking forward to your more detailed overview. 

As to the ids, we also came to the same conclusion regarding UUID vs String. Also, our use case does not allow for generating Long identifiers.

I was able to convert the library to use StringType. However, it needed quite a lot of changes especially in the tests. We ended up commenting out quite a few test-cases. Can you point me to your experiment using StringType, if you still have it? I'm now working on parameterizing the library so that it can support both Long and String. Did you explore that path already?

**Comment by s1ck** [comment]
Hey. Unfortunately, there is no branch that contains our previous experiments. We thought about generalizing the identifier type but didn't actually go forward with it. If you want me to have a look at what you've already done, you can point me to a branch or open a PR.

**Comment by ram-senth** [comment]
Thanks a lot for responding. I got a bit sidetracked and forgot to check this thread. Will forward the PR soon.

**Comment by s1ck** [comment]
Hey @ram-senth ! Just wanted to ping you about the status of the id type changes. We are currently having some discussions within the CAPS team and I was wondering if we should sync at some point. wdyt?

**Comment by pstutz** [comment]
@ram-senth we just merged our new ID representation, CAPS identifiers are now of `BinaryType`. You could already cast your string UUIDs to `BinaryType` and that should just work as an ID column.
