### ISSUE TITLE
Feature Request: Support Sparklyr

### ISSUE THREAD

**Issue by harryprince** [opencypher/cypher-for-apache-spark#880]
Graph Mining is very tidy in the R ecosystem by [tidygraph](https://github.com/thomasp85/tidygraph) right now.

Wish Cypher style could integrate to graph mining tidy workflow in R.

related discuss on [spakrlyr repo](https://github.com/rstudio/sparklyr/issues/1953)

**Comment by Mats-SX** [comment]
Hello @harryprince and thanks for reaching out to us!

Could you explain in more detail what supporting Sparklyr would actually mean for CAPS? How does it differ from Apache Spark's own R API (`SparkR`)?

I should point out that we do not have any plans currently on developing an R API for CAPS, mostly due to capacity limitations. However, since (parts of) CAPS are currently being written into Spark itself ([SPARK-25994](https://issues.apache.org/jira/browse/SPARK-25994)), it is very likely that an R API will be requested for Cypher as well in that process.

**Comment by harryprince** [comment]
[Sparklyr](https://spark.rstudio.com) is a Spark Interface powered by RStudio, which built a great plugin system upon `dbplyr`,`dplyr`.  
Over the three years, Sparklyr connectted lots of exist Spark Scala Pacakge, such as [sparkxgb](https://github.com/rstudio/sparkxgb), [graphframes](https://github.com/rstudio/graphframes),[geospark](https://github.com/harryprince/geospark), [sparktf](https://github.com/rstudio/sparktf) and so on. 

## Reference
https://cosx.org/2018/05/sparkr-vs-sparklyr

**Comment by harryprince** [comment]
I think OpenCyper built a great CAPS abstraction, which is a DataFrame interface like `tidygraph`.
Previously, [`graphframes`](https://github.com/rstudio/graphframes) package doing the similar things, however, it is far from the `tidy` way and do not support Cypher, the standard graph grammar.

The `graphframes` is developed by RStudio with few human power but easy and robust to use.

**Comment by Mats-SX** [comment]
@harryprince I think our best bet here is to follow the progress of moving CAPS into Spark itself, and then work with the Spark community to define an R interface within Spark itself. We do not yet know the exact shape of the SparkCypher API (which is larger than the `.cypher(queryString)` method), and so I would advise that we do not spend time trying to wrap it through to R (or Python) until it has been finalised for Spark 3.0.
